import type { Bookmark, ExtractedPage } from "./types";
type Stored = ExtractedPage & { id: string; embedding: number[]; createdAt: string; lastAccessedAt: string | null };
const NAME = "lembralink-local"; const STORE = "bookmarks";
function db() { return new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open(NAME, 1); r.onupgradeneeded = () => r.result.createObjectStore(STORE, { keyPath: "id" }); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
async function all() { const d = await db(); return new Promise<Stored[]>((resolve, reject) => { const r = d.transaction(STORE, "readonly").objectStore(STORE).getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
async function put(item: Stored) { const d = await db(); return new Promise<void>((resolve, reject) => { const r = d.transaction(STORE, "readwrite").objectStore(STORE).put(item); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); }
const view = (b: Stored, similarity?: number): Bookmark => ({ id: b.id, title: b.title, original_url: b.url, summary: b.description ?? b.content.slice(0, 280), category: null, page_type: null, tags: [], similarity, created_at: b.createdAt, last_accessed_at: b.lastAccessedAt, indexed_at: b.createdAt });
export async function saveLocal(page: ExtractedPage, embedding: number[]) { const existing = (await all()).find((item) => item.url === page.url); const item: Stored = { ...page, embedding, id: existing?.id ?? crypto.randomUUID(), createdAt: existing?.createdAt ?? new Date().toISOString(), lastAccessedAt: existing?.lastAccessedAt ?? null }; await put(item); return view(item); }
export async function searchLocal(embedding: number[], limit: number) { return (await all()).map((b) => view(b, b.embedding.reduce((sum, n, i) => sum + n * (embedding[i] ?? 0), 0))).sort((a, b) => (b.similarity ?? 0) - (a.similarity ?? 0)).slice(0, limit); }
export async function touchLocal(id: string) { const item = (await all()).find((b) => b.id === id); if (!item) throw new Error("Favorito não encontrado."); item.lastAccessedAt = new Date().toISOString(); await put(item); return { lastAccessedAt: item.lastAccessedAt }; }
export async function deleteLocal(id: string) { const d = await db(); return new Promise<void>((resolve, reject) => { const r = d.transaction(STORE, "readwrite").objectStore(STORE).delete(id); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); }
export async function clearLocal() { const d = await db(); return new Promise<void>((resolve, reject) => { const r = d.transaction(STORE, "readwrite").objectStore(STORE).clear(); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); }
