import { DEFAULT_MAX_RESULTS, DEFAULT_MIN_SIMILARITY, normalizeSupabaseUrl, type RuntimeConfig } from "./config";
import type { Bookmark, ImportCandidate, ImportProgress, RequestMessage, ResponseMessage, UsageMode } from "./types";
const app = document.querySelector<HTMLDivElement>("#app")!; let mode: UsageMode = "local"; let config: RuntimeConfig | null = null; let bookmarks: Bookmark[] = [];
const escape = (value: string) => { const e = document.createElement("span"); e.textContent = value; return e.innerHTML; };
async function call<T>(message: RequestMessage) { const response = await chrome.runtime.sendMessage(message) as ResponseMessage<T>; if (!response.ok) throw new Error(response.error); return response.data; }
function brand() { return `<div class="brand-title"><img class="brand-icon" src="icons/icon.svg" alt="" /><div><h1>LembraLink</h1><small>Salve agora. Encontre quando precisar.</small></div></div>`; }
function status(message: string, error = false) { document.querySelector<HTMLDivElement>("#status")!.innerHTML = `<p class="notice ${error ? "error" : "success"}">${escape(message)}</p>`; }
function modeSelector() { return `<fieldset class="mode"><legend>Onde usar seus favoritos?</legend><label><input type="radio" name="mode" value="local" ${mode === "local" ? "checked" : ""}/> Local — simples e sem conta</label><label><input type="radio" name="mode" value="online" ${mode === "online" ? "checked" : ""}/> Online — Supabase e sincronização</label></fieldset>`; }
function bindMode() { document.querySelectorAll<HTMLInputElement>("input[name=mode]").forEach((input) => input.addEventListener("change", async () => { mode = input.value as UsageMode; await call({ type: "mode.set", mode }); render(); })); }
function parse(html: string) { const doc = new DOMParser().parseFromString(html, "text/html"); const seen = new Set<string>(); const list: ImportCandidate[] = []; doc.querySelectorAll<HTMLAnchorElement>("a[href]").forEach((a) => { try { const url = new URL(a.href); if (!/^https?:$/.test(url.protocol)) return; url.hash = ""; if (!seen.has(url.href)) { seen.add(url.href); list.push({ title: a.textContent?.trim() || url.hostname, url: url.href }); } } catch {} }); return list; }
function renderConfig(message = "") { app.innerHTML = `${brand()}${modeSelector()}<p>Informe os valores públicos do seu projeto Supabase.</p><form id="config"><label>URL do Supabase<input id="url" value="${escape(config?.supabaseUrl ?? "")}" required /></label><label>Chave publishable<input id="key" value="${escape(config?.publishableKey ?? "")}" required /></label><label>Similaridade mínima<input id="min" type="number" min="0" max="1" step="0.05" value="${config?.minSimilarity ?? DEFAULT_MIN_SIMILARITY}" /></label><label>Máximo de resultados<input id="max" type="number" min="1" max="20" value="${config?.maxResults ?? DEFAULT_MAX_RESULTS}" /></label><button>Autorizar e salvar</button></form><div id="status"><p class="notice error">${escape(message)}</p></div>`; bindMode(); document.querySelector<HTMLFormElement>("#config")!.addEventListener("submit", async (event) => { event.preventDefault(); try { const supabaseUrl = normalizeSupabaseUrl(document.querySelector<HTMLInputElement>("#url")!.value); if (!await chrome.permissions.request({ origins: [`${supabaseUrl}/*`] })) throw new Error("Autorize o Supabase para continuar."); config = await call({ type: "settings.save", supabaseUrl, publishableKey: document.querySelector<HTMLInputElement>("#key")!.value, minSimilarity: Number(document.querySelector<HTMLInputElement>("#min")!.value), maxResults: Number(document.querySelector<HTMLInputElement>("#max")!.value) }); render(); } catch (error) { renderConfig(error instanceof Error ? error.message : "Configuração inválida."); } }); }
function renderLogin(message = "") { app.innerHTML = `${brand()}${modeSelector()}<form id="login"><label>Email<input id="email" type="email" required /></label><button>Enviar link de acesso</button></form><div id="status"><p class="notice error">${escape(message)}</p></div>`; bindMode(); document.querySelector<HTMLFormElement>("#login")!.addEventListener("submit", async (event) => { event.preventDefault(); const email = document.querySelector<HTMLInputElement>("#email")!.value; try { await call({ type: "auth.sendOtp", email }); app.innerHTML = `${brand()}${modeSelector()}<form id="code"><label>Código ou link recebido<input id="token" required /></label><button>Entrar</button></form><div id="status"></div>`; bindMode(); document.querySelector<HTMLFormElement>("#code")!.addEventListener("submit", async (e) => { e.preventDefault(); const token = document.querySelector<HTMLInputElement>("#token")!.value; try { if (token.startsWith("https://")) await call({ type: "auth.verifyMagicLink", link: token }); else await call({ type: "auth.verifyOtp", email, token }); renderApp(); } catch (x) { renderLogin(x instanceof Error ? x.message : "Falha no login."); } }); } catch (error) { renderLogin(error instanceof Error ? error.message : "Falha no login."); } }); }
function cards() { return bookmarks.map((b) => `<article class="bookmark"><header><a href="${escape(b.original_url)}" data-open="${b.id}">${escape(b.title)}</a><button class="danger" data-delete="${b.id}">Excluir</button></header><p>${escape(b.summary)}</p><small>Similaridade: ${(b.similarity ?? 0).toFixed(2)}</small></article>`).join("") || "<p>Nenhum resultado ainda.</p>"; }
function renderApp() { app.innerHTML = `${brand()}${modeSelector()}<p>${mode === "local" ? "Favoritos ficam somente neste perfil do navegador." : "Favoritos sincronizados com seu projeto Supabase."}</p><h2>Página atual</h2><button id="save">Salvar esta página</button><div id="status"></div><h2>Importar favoritos</h2><form id="import"><label>Arquivo HTML<input id="file" type="file" accept=".html,text/html" required /></label><label>Limite<input id="limit" type="number" min="1" max="500" value="50" /></label><button>Autorizar e importar</button></form><div id="import-status"></div><h2>Buscar favoritos</h2><form id="search-form" class="row"><input id="query" required placeholder="Ex.: configurar o Spark localmente"/><button>Buscar</button></form><button class="danger" id="clear">Excluir todos os favoritos deste modo</button><div id="results">${cards()}</div>`; bindMode(); document.querySelector<HTMLButtonElement>("#save")!.onclick = async () => { try { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab.id) throw new Error("Aba indisponível."); status(mode === "local" ? "Preparando o modelo local…" : "Salvando…"); await call({ type: "bookmark.save", tabId: tab.id }); status("Favorito salvo."); } catch (e) { status(e instanceof Error ? e.message : "Falha ao salvar.", true); } }; document.querySelector<HTMLFormElement>("#search-form")!.onsubmit = async (e) => { e.preventDefault(); try { const result = await call<{ results: Bookmark[] }>({ type: "bookmark.search", query: document.querySelector<HTMLInputElement>("#query")!.value, limit: config?.maxResults ?? 10 }); bookmarks = result.results; document.querySelector<HTMLDivElement>("#results")!.innerHTML = cards(); bindCards(); } catch (x) { status(x instanceof Error ? x.message : "Falha na busca.", true); } }; document.querySelector<HTMLButtonElement>("#clear")!.onclick = async () => { if (!confirm(`Excluir todos os favoritos ${mode === "local" ? "locais" : "online"}?`)) return; await call({ type: "bookmark.clear" }); bookmarks = []; renderApp(); }; document.querySelector<HTMLFormElement>("#import")!.onsubmit = async (e) => { e.preventDefault(); const file = document.querySelector<HTMLInputElement>("#file")!.files?.[0]; if (!file) return; try { if (!await chrome.permissions.request({ origins: ["<all_urls>"] })) throw new Error("Autorize o acesso aos links."); const items = parse(await file.text()).slice(0, Number(document.querySelector<HTMLInputElement>("#limit")!.value)); await call({ type: "import.start", items }); pollImport(); } catch (x) { status(x instanceof Error ? x.message : "Falha ao iniciar importação.", true); } }; bindCards(); }
function bindCards() { document.querySelectorAll<HTMLAnchorElement>("[data-open]").forEach((a) => a.onclick = async (e) => { e.preventDefault(); await call({ type: "bookmark.access", id: a.dataset.open! }); await chrome.tabs.create({ url: a.href }); }); document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach((b) => b.onclick = async () => { await call({ type: "bookmark.delete", id: b.dataset.delete! }); bookmarks = bookmarks.filter((x) => x.id !== b.dataset.delete); renderApp(); }); }
function pollImport() { const timer = setInterval(async () => { const p = await call<ImportProgress>({ type: "import.status" }); const host = document.querySelector<HTMLDivElement>("#import-status"); if (host) host.textContent = `${p.saved + p.failed}/${p.total}: ${p.saved} salvos, ${p.failed} falhas.`; if (p.done) clearInterval(timer); }, 1200); }
async function render() { mode = await call<UsageMode>({ type: "mode.get" }); config = await call<RuntimeConfig | null>({ type: "settings.get" }); if (mode === "local") return renderApp(); if (!config) return renderConfig(); try { await call({ type: "auth.session" }); renderApp(); } catch { renderLogin(); } }
void render();
