import { DEFAULT_MAX_RESULTS, DEFAULT_MIN_SIMILARITY, normalizeSupabaseUrl, type RuntimeConfig } from "./config";
import type { Bookmark, ImportCandidate, ImportProgress, RequestMessage, ResponseMessage, UsageMode } from "./types";
const app = document.querySelector<HTMLDivElement>("#app")!; let mode: UsageMode = "local"; let config: RuntimeConfig | null = null; let bookmarks: Bookmark[] = [];
const escape = (v: string) => { const e = document.createElement("span"); e.textContent = v; return e.innerHTML; };
async function call<T>(message: RequestMessage) { const r = await chrome.runtime.sendMessage(message) as ResponseMessage<T>; if (!r.ok) throw new Error(r.error); return r.data; }
const brand = () => `<div class="brand-title"><img class="brand-icon" src="icons/icon.svg" alt=""/><div><h1>LembraLink</h1><small>Salve agora. Encontre quando precisar.</small></div></div>`;
const selector = () => `<fieldset class="mode"><legend>Modo</legend><label><input type="radio" name="mode" value="local" ${mode === "local" ? "checked" : ""}/> local</label><label><input type="radio" name="mode" value="online" ${mode === "online" ? "checked" : ""}/> online</label></fieldset>`;
function bindMode() { document.querySelectorAll<HTMLInputElement>("input[name=mode]").forEach((i) => i.onchange = async () => { mode = i.value as UsageMode; await call({ type: "mode.set", mode }); render(); }); }
function cards() { return bookmarks.map((b) => `<article class="bookmark"><header><a href="${escape(b.original_url)}" data-open="${b.id}">${escape(b.title)}</a><button class="danger" data-delete="${b.id}">Excluir</button></header><p>${escape(b.summary)}</p><small>Similaridade: ${(b.similarity ?? 0).toFixed(2)}</small></article>`).join("") || "<p>Nenhum resultado ainda.</p>"; }
function bindCards() { document.querySelectorAll<HTMLAnchorElement>("[data-open]").forEach((a) => a.onclick = async (e) => { e.preventDefault(); await call({ type: "bookmark.access", id: a.dataset.open! }); await chrome.tabs.create({ url: a.href }); }); document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach((b) => b.onclick = async () => { await call({ type: "bookmark.delete", id: b.dataset.delete! }); bookmarks = bookmarks.filter((x) => x.id !== b.dataset.delete); renderApp(); }); }
function parse(html: string) { const doc = new DOMParser().parseFromString(html, "text/html"); const seen = new Set<string>(); const result: ImportCandidate[] = []; doc.querySelectorAll<HTMLAnchorElement>("a[href]").forEach((a) => { try { const url = new URL(a.href); if (/^https?:$/.test(url.protocol) && !seen.has(url.href)) { seen.add(url.href); result.push({ title: a.textContent?.trim() || url.hostname, url: url.href }); } } catch {} }); return result; }
function tabButtons() { return `<div class="tabs"><button class="secondary active" data-tab="use">Favoritos</button><button class="secondary" data-tab="settings">Configurações</button></div>`; }
function bindTabs() { document.querySelectorAll<HTMLButtonElement>("[data-tab]").forEach((button) => button.onclick = () => { const current = button.dataset.tab!; document.querySelectorAll<HTMLElement>("[data-panel]").forEach((panel) => panel.hidden = panel.dataset.panel !== current); document.querySelectorAll<HTMLButtonElement>("[data-tab]").forEach((tab) => tab.classList.toggle("active", tab === button)); }); }
function renderApp() {
  app.innerHTML = `${brand()}${tabButtons()}<section data-panel="use"><p>${mode === "local" ? "Favoritos neste navegador." : "Favoritos no seu Supabase."}</p><h2>Página atual</h2><button id="save">Salvar esta página</button><div id="status"></div><h2>Buscar favoritos</h2><form id="search" class="row"><input id="query" required placeholder="Ex.: configurar o Spark localmente"/><button>Buscar</button></form><div id="results">${cards()}</div></section><section data-panel="settings" hidden>${selector()}${mode === "online" ? `<p>Modo online usa a configuração e a sessão do Supabase.</p><button class="secondary" id="online-settings">Editar Supabase</button>` : `<p>O modo local não sincroniza entre navegadores ou máquinas.</p>`}<h2>Importar favoritos</h2><form id="import"><label>Arquivo HTML<input id="file" type="file" accept=".html,text/html" required/></label><label>Limite<input id="limit" type="number" min="1" max="500" value="50"/></label><button>Autorizar e importar</button></form><div id="import-status"></div><h2>Dados</h2><button class="danger" id="clear">Excluir todos os favoritos deste modo</button></section>`;
  bindTabs(); bindMode(); bindCards(); document.querySelector<HTMLButtonElement>("#online-settings")?.addEventListener("click", () => renderConfig());
  document.querySelector<HTMLButtonElement>("#save")!.onclick = async () => { try { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab.id) throw new Error("Aba indisponível."); const host = document.querySelector<HTMLDivElement>("#status")!; host.textContent = mode === "local" ? "Preparando o modelo local…" : "Salvando…"; await call({ type: "bookmark.save", tabId: tab.id }); host.textContent = "Favorito salvo."; } catch (e) { document.querySelector<HTMLDivElement>("#status")!.textContent = e instanceof Error ? e.message : "Falha ao salvar."; } };
  document.querySelector<HTMLFormElement>("#search")!.onsubmit = async (e) => { e.preventDefault(); try { const r = await call<{ results: Bookmark[] }>({ type: "bookmark.search", query: document.querySelector<HTMLInputElement>("#query")!.value, limit: config?.maxResults ?? 10 }); bookmarks = r.results; document.querySelector<HTMLDivElement>("#results")!.innerHTML = cards(); bindCards(); } catch (x) { document.querySelector<HTMLDivElement>("#status")!.textContent = x instanceof Error ? x.message : "Falha na busca."; } };
  document.querySelector<HTMLButtonElement>("#clear")!.onclick = async () => { if (confirm(`Excluir todos os favoritos ${mode}?`)) { await call({ type: "bookmark.clear" }); bookmarks = []; renderApp(); } };
  document.querySelector<HTMLFormElement>("#import")!.onsubmit = async (e) => { e.preventDefault(); const f = document.querySelector<HTMLInputElement>("#file")!.files?.[0]; if (!f) return; try { if (!await chrome.permissions.request({ origins: ["<all_urls>"] })) throw new Error("Autorize o acesso aos links."); await call({ type: "import.start", items: parse(await f.text()).slice(0, Number(document.querySelector<HTMLInputElement>("#limit")!.value)) }); const timer = setInterval(async () => { const p = await call<ImportProgress>({ type: "import.status" }); const host = document.querySelector<HTMLDivElement>("#import-status"); if (host) host.textContent = `${p.saved + p.failed}/${p.total}: ${p.saved} salvos, ${p.failed} falhas.`; if (p.done) clearInterval(timer); }, 1200); } catch (x) { document.querySelector<HTMLDivElement>("#import-status")!.textContent = x instanceof Error ? x.message : "Falha ao importar."; } };
}
function renderConfig(message = "") { app.innerHTML = `${brand()}${selector()}<p>Configuração do modo online.</p><form id="config"><label>URL do Supabase<input id="url" value="${escape(config?.supabaseUrl ?? "")}" required/></label><label>Chave publishable<input id="key" value="${escape(config?.publishableKey ?? "")}" required/></label><label>Similaridade mínima<input id="min" type="number" min="0" max="1" step="0.05" value="${config?.minSimilarity ?? DEFAULT_MIN_SIMILARITY}"/></label><label>Máximo de resultados<input id="max" type="number" min="1" max="20" value="${config?.maxResults ?? DEFAULT_MAX_RESULTS}"/></label><button>Autorizar e salvar</button></form><p class="notice error">${escape(message)}</p>`; bindMode(); document.querySelector<HTMLFormElement>("#config")!.onsubmit = async (e) => { e.preventDefault(); try { const supabaseUrl = normalizeSupabaseUrl(document.querySelector<HTMLInputElement>("#url")!.value); if (!await chrome.permissions.request({ origins: [`${supabaseUrl}/*`] })) throw new Error("Autorize o Supabase."); config = await call({ type: "settings.save", supabaseUrl, publishableKey: document.querySelector<HTMLInputElement>("#key")!.value, minSimilarity: Number(document.querySelector<HTMLInputElement>("#min")!.value), maxResults: Number(document.querySelector<HTMLInputElement>("#max")!.value) }); render(); } catch (x) { renderConfig(x instanceof Error ? x.message : "Configuração inválida."); } }; }
function renderLogin(message = "") { app.innerHTML = `${brand()}${selector()}<form id="login"><label>Email<input id="email" type="email" required/></label><button>Enviar link de acesso</button></form><p class="notice error">${escape(message)}</p>`; bindMode(); document.querySelector<HTMLFormElement>("#login")!.onsubmit = async (e) => { e.preventDefault(); const email = document.querySelector<HTMLInputElement>("#email")!.value; try { await call({ type: "auth.sendOtp", email }); app.innerHTML = `${brand()}${selector()}<form id="code"><label>Código ou link<input id="token" required/></label><button>Entrar</button></form>`; bindMode(); document.querySelector<HTMLFormElement>("#code")!.onsubmit = async (event) => { event.preventDefault(); try { const token = document.querySelector<HTMLInputElement>("#token")!.value; if (token.startsWith("https://")) await call({ type: "auth.verifyMagicLink", link: token }); else await call({ type: "auth.verifyOtp", email, token }); renderApp(); } catch (x) { renderLogin(x instanceof Error ? x.message : "Falha no login."); } }; } catch (x) { renderLogin(x instanceof Error ? x.message : "Falha no login."); } }; }
async function render() { mode = await call<UsageMode>({ type: "mode.get" }); config = await call<RuntimeConfig | null>({ type: "settings.get" }); if (mode === "online") { if (!config) return renderConfig(); try { await call({ type: "auth.session" }); } catch { return renderLogin(); } } renderApp(); }
void render();
